=== tasbox-org/docs/schema.json
{
  "$ref": "#/definitions/Library",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ArrayType": {
      "additionalProperties": false,
      "properties": {
        "items": {
          "$ref": "#/definitions/Type"
        },
        "type": {
          "const": "array",
          "type": "string"
        }
      },
      "required": [
        "type",
        "items"
      ],
      "type": "object"
    },
    "Class": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "properties": {
          "items": {
            "$ref": "#/definitions/ClassProperty"
          },
          "type": "array"
        },
        "realms": {
          "items": {
            "$ref": "#/definitions/Realm"
          },
          "type": "array"
        }
      },
      "required": [
        "name",
        "properties"
      ],
      "type": "object"
    },
    "ClassProperty": {
      "additionalProperties": false,
      "properties": {
        "defaultValue": {
          "type": [
            "string",
            "number",
            "boolean"
          ]
        },
        "description": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "number"
          ]
        },
        "optional": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/Type"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "Constant": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "number"
          ]
        },
        "optional": {
          "type": "boolean"
        },
        "realms": {
          "items": {
            "$ref": "#/definitions/Realm"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/Type"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "Enum": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "realms": {
          "items": {
            "$ref": "#/definitions/Realm"
          },
          "type": "array"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "name",
        "values"
      ],
      "type": "object"
    },
    "FunctionParameter": {
      "additionalProperties": false,
      "properties": {
        "defaultValue": {
          "type": [
            "string",
            "number",
            "boolean"
          ]
        },
        "description": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "number"
          ]
        },
        "optional": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/Type"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "FunctionProperty": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "parameters": {
          "items": {
            "$ref": "#/definitions/FunctionParameter"
          },
          "type": "array"
        },
        "realms": {
          "items": {
            "$ref": "#/definitions/Realm"
          },
          "type": "array"
        },
        "returns": {
          "items": {
            "$ref": "#/definitions/Property"
          },
          "type": "array"
        },
        "section": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "parameters",
        "returns"
      ],
      "type": "object"
    },
    "FunctionType": {
      "additionalProperties": false,
      "properties": {
        "parameters": {
          "items": {
            "$ref": "#/definitions/Property"
          },
          "type": "array"
        },
        "returns": {
          "items": {
            "$ref": "#/definitions/Property"
          },
          "type": "array"
        },
        "type": {
          "const": "function",
          "type": "string"
        }
      },
      "required": [
        "type",
        "parameters",
        "returns"
      ],
      "type": "object"
    },
    "Library": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "classes": {
          "items": {
            "$ref": "#/definitions/Class"
          },
          "type": "array"
        },
        "constants": {
          "items": {
            "$ref": "#/definitions/Constant"
          },
          "type": "array"
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          ]
        },
        "enums": {
          "items": {
            "$ref": "#/definitions/Enum"
          },
          "type": "array"
        },
        "events": {
          "items": {
            "$ref": "#/definitions/FunctionProperty"
          },
          "type": "array"
        },
        "functions": {
          "items": {
            "$ref": "#/definitions/FunctionProperty"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        },
        "realms": {
          "description": "Default realms for all constants, functions, enums, classes and events in this library. If not defined, realm is unknown (i.e. documentation needs updating).",
          "items": {
            "$ref": "#/definitions/Realm"
          },
          "type": "array"
        }
      },
      "required": [
        "$schema",
        "name"
      ],
      "type": "object"
    },
    "PrimitiveType": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/ArrayType"
        },
        {
          "$ref": "#/definitions/FunctionType"
        }
      ]
    },
    "Property": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "number"
          ]
        },
        "optional": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/Type"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "Realm": {
      "enum": [
        "menu",
        "client",
        "server"
      ],
      "type": "string"
    },
    "Type": {
      "anyOf": [
        {
          "$ref": "#/definitions/PrimitiveType"
        },
        {
          "items": {
            "$ref": "#/definitions/PrimitiveType"
          },
          "type": "array"
        }
      ]
    }
  }
}

=== tasbox-org/docs/src/engine.json
{
  "$schema": "../schema.json",
  "name": "Engine",
  "realms": ["menu", "client", "server"],
  "description": "API for engine-related functions.",
  "functions": [
    {
      "name": "getCurrentTime",
      "description": "Gets the current time.",
      "parameters": [],
      "returns": [
        {
          "name": "time",
          "description": "The current time in seconds.",
          "type": "number"
        }
      ]
    },
    {
      "name": "quit",
      "description": "Quits the game.",
      "parameters": [],
      "returns": []
    },
    {
      "name": "setAddonGlobals",
      "description": "Sets the global environment for addons.",
      "parameters": [
        {
          "name": "callback",
          "description": "The callback which returns the global environment used for addons.",
          "type": {
            "type": "function",
            "parameters": [
              {
                "name": "sandbox",
                "type": "sandbox",
                "description": "The sandbox used for the addons."
              },
              {
                "name": "require",
                "type": {
                  "type": "function",
                  "parameters": [
                    {
                      "name": "path",
                      "type": "string",
                      "description": "The path to the module."
                    }
                  ],
                  "returns": [
                    {
                      "name": "module",
                      "type": "any",
                      "description": "The return value of the executed file."
                    }
                  ]
                }
              }
            ],
            "returns": [
              {
                "name": "globals",
                "type": "table",
                "description": "The globals to set."
              }
            ]
          }
        }
      ],
      "returns": []
    }
  ],
  "constants": [
    {
      "name": "WORLD_FORWARD_DIRECTION",
      "description": "The forward direction of the world.",
      "type": "vector"
    },
    {
      "name": "WORLD_UP_DIRECTION",
      "description": "The up direction of the world.",
      "type": "vector"
    },
    {
      "name": "WORLD_RIGHT_DIRECTION",
      "description": "The right direction of the world.",
      "type": "vector"
    },
    {
      "name": "THIS_REALM",
      "description": "The realm this script is executing in (Menu, Server or Client).",
      "type": "Engine.Realm"
    }
  ],
  "enums": [
    {
      "name": "Realm",
      "description": "The realms or environments in which scripts can execute.",
      "values": ["Menu", "Server", "Client"]
    }
  ],
  "events": [
    {
      "name": "tick",
      "description": "Fires every frame.",
      "parameters": [
        {
          "name": "deltaTime",
          "description": "The time in seconds since the last frame.",
          "type": "number"
        }
      ],
      "returns": []
    }
  ]
}
